# Control Plane Stack

services:
  control-gateway:
    build: 
      context: ../../
      dockerfile: control/gateway/Dockerfile
    image: control-gateway-image
    ports:
      - "${CONTROL_GATEWAY_PORT:-80}:80"
    networks:
      - control-network
      - sut-network

  control-orchestrator:
    build: 
      context: ../../
      dockerfile: control/orchestrator/Dockerfile
    image: control-orchestrator-image
    expose:
      - "80"
    networks:
      - control-network
      - load-network