# Observability Stack using Prometheus, Grafana, Loki, Tempo, and Pyroscope

services:
  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - ../../observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
      - ../../observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    networks:
      - observability-network

  prometheus:
    image: prom/prometheus:v2.53.1
    volumes:
      - ../../observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    networks:
      - observability-network
      - sut-network

  loki:
    image: grafana/loki:3.1.0
    command: -config.file=/etc/loki/loki.yml
    ports:
      - "${LOKI_PORT:-3100}:3100"
    volumes:
      - ../../observability/loki/loki.yml:/etc/loki/loki.yml
      - loki-data:/loki
    networks:
      - observability-network

  tempo:
    image: grafana/tempo:2.6.0
    command: -config.file=/etc/tempo/tempo.yml
    ports:
      - "${TEMPO_HTTP_PORT:-3200}:3200"   # Tempo HTTP
      - "${TEMPO_GRPC_PORT:-4317}:4317"   # OTLP gRPC
      - "${TEMPO_OTLP_PORT:-4318}:4318"   # OTLP HTTP
    volumes:
      - ../../observability/tempo/tempo.yml:/etc/tempo/tempo.yml
      - tempo-data:/var/tempo
    networks:
      - observability-network
  
  pyroscope:
    image: grafana/pyroscope:1.7.1
    ports:
      - "${PYROSCOPE_PORT:-4040}:4040"
    command:
      - "server"
    volumes:
      - pyroscope-data:/var/lib/pyroscope
    networks:
      - observability-network

volumes:
  prometheus-data:
  grafana-data:
  loki-data:
  tempo-data:
  pyroscope-data:
